### ISSUE TITLE
Error compiling with linux

### ISSUE THREAD

**Issue by MalikSploit** [poupou9779/z2048#3]

**Comment by poupou9779** [comment]
This is not an _error_ but a _warning_. `i_log2` is a function defined in `functions.c` (https://github.com/poupou9779/z2048/blob/master/src/functions.c#L271). The warning appears because there is no prototype for this function and it is defined after the function `play` that still uses it. You can either add a prototype do `functions.h` or move the function to the top of `functions.c` if you want to get rid of this warning.

You can also change `log2` by `i_log2` in the definition of `MAX_VALUE` in `functions.h`if you want to remove the other warning.
